### ISSUE TITLE
 from src.config import get_config  / ImportError: No module named config

### ISSUE THREAD

**Issue by yacinemrabet1** [peacecwz/shazam-demo#3]
Traceback (most recent call last):
  File "listen.py", line 10, in <module>
    from src.config import get_config
ImportError: No module named config

**Comment by josewweee** [comment]
comment "from src.config import get_config" in listen.py and it'll work flawless

**Comment by peacecwz** [comment]
@yacinemrabet1 I removed unused config import in last commit
